# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'disp_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgDispImage(object):
    def setupUi(self, dlgDispImage):
        dlgDispImage.setObjectName("dlgDispImage")
        dlgDispImage.resize(1096, 843)
        self.lblImage = QtWidgets.QLabel(dlgDispImage)
        self.lblImage.setGeometry(QtCore.QRect(10, 20, 1071, 721))
        self.lblImage.setText("")
        self.lblImage.setObjectName("lblImage")
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgDispImage)
        self.buttonBox.setGeometry(QtCore.QRect(985, 790, 81, 31))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.btnPrev = QtWidgets.QPushButton(dlgDispImage)
        self.btnPrev.setGeometry(QtCore.QRect(30, 800, 89, 25))
        self.btnPrev.setObjectName("btnPrev")
        self.btnNext = QtWidgets.QPushButton(dlgDispImage)
        self.btnNext.setGeometry(QtCore.QRect(140, 800, 89, 25))
        self.btnNext.setObjectName("btnNext")
        self.lblIndex = QtWidgets.QLabel(dlgDispImage)
        self.lblIndex.setGeometry(QtCore.QRect(280, 800, 201, 16))
        self.lblIndex.setText("")
        self.lblIndex.setObjectName("lblIndex")

        self.retranslateUi(dlgDispImage)
        self.btnPrev.clicked.connect(dlgDispImage.prev_clicked)
        self.btnNext.clicked.connect(dlgDispImage.next_clicked)
        QtCore.QMetaObject.connectSlotsByName(dlgDispImage)

    def retranslateUi(self, dlgDispImage):
        _translate = QtCore.QCoreApplication.translate
        dlgDispImage.setWindowTitle(_translate("dlgDispImage", "Dialog"))
        self.btnPrev.setText(_translate("dlgDispImage", "Prev"))
        self.btnNext.setText(_translate("dlgDispImage", "Next"))
