# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_dup.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1021, 850)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 641, 791))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblImage = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblImage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblImage.setObjectName("lblImage")
        self.verticalLayout.addWidget(self.lblImage)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(640, 0, 381, 791))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.btnCancel = QtWidgets.QDialogButtonBox(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(935, 820, 81, 23))
        self.btnCancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.btnCancel.setCenterButtons(False)
        self.btnCancel.setObjectName("btnCancel")
        self.btnPrev = QtWidgets.QPushButton(Dialog)
        self.btnPrev.setGeometry(QtCore.QRect(10, 810, 75, 23))
        self.btnPrev.setObjectName("btnPrev")
        self.btnNext = QtWidgets.QPushButton(Dialog)
        self.btnNext.setGeometry(QtCore.QRect(110, 810, 75, 23))
        self.btnNext.setObjectName("btnNext")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblImage.setText(_translate("Dialog", "TextLabel"))
        self.btnPrev.setText(_translate("Dialog", "Previous"))
        self.btnNext.setText(_translate("Dialog", "Next"))
